spring:
  security:
    user:
      password: "{cipher}AECL9kujF/3ls78VYFUOjAz7IVgUF2SFLibX4z+FlGSIORBkcBkY+YZOYHV6jhyt/Wdt8DKowquulVwXRoddWn6JdEXEajK3tybScTWHsb44DFgORz7MP675Za2+rTTw1JU="
      name: "bstarke"
welcome:
  message: "Hello Earthling"