spring:
  jpa:
    show-sql: true
endpoints:
  enabled: true
  sensitive: false
logging:
  level:
    org.flbc: "DEBUG"
    org.springframework: "INFO"
    org.hibernate: "INFO"
eggdrop:
  ageGroups:
    -
      name: "0 to 2"
      min: 0
      max: 2
    -
      name: "3 to 5"
      min: 3
      max: 5
    -
      name: "6 to 8"
      min: 6
      max: 8
    -
      name: "9 to 10"
      min: 9
      max: 10
    -
      name: "Over Age"
      min: 11
      max: 99