spring:
  datasource:
    validation-query: "select 1"
    test-on-borrow: true
  jpa:
    database-platform: "org.hibernate.dialect.MySQL5Dialect"
    show-sql: false
    hibernate:
      ddl-auto: "update"
endpoints:
  enabled: false
  health:
    enabled: true
  info:
    enabled: true
logging:
  level:
    org.flbc: "DEBUG"
    org.springframework: "WARN"
    org.hibernate: "WARN"
server:
  tomcat:
    remote_ip_header: "x-forwarded-for"
    protocol_header: "x-forwarded-proto"
eggdrop:
  ageGroups:
    -
      name: "0 to 1"
      min: 0
      max: 1
    -
      name: "2 to 3"
      min: 2
      max: 3
    -
      name: "4 to 6"
      min: 4
      max: 6
    -
      name: "7 to 10"
      min: 7
      max: 12
    -
      name: "Over Age"
      min: 13
      max: 99