spring:
  datasource:
    validation-query: "select 1"
    test-on-borrow: true
  jpa:
    database-platform: "org.hibernate.dialect.MySQLDialect"
    show-sql: false
    hibernate:
      ddl-auto: "update"
endpoints:
  enabled: false
  health:
    enabled: true
  info:
    enabled: true
logging:
  level:
    org.flbc: "INFO"
    org.springframework: "WARN"
    org.hibernate: "WARN"
server:
  tomcat:
    remote_ip_header: "x-forwarded-for"
    protocol_header: "x-forwarded-proto"